-- Insert de todas las comunas

insert into par_comuna (IdRegion, Descripcion) values (32, 'Arica')
insert into par_comuna (IdRegion, Descripcion) values (32, 'Camarones')
insert into par_comuna (IdRegion, Descripcion) values (32, 'Putre')
insert into par_comuna (IdRegion, Descripcion) values (32, 'General Lagos')
insert into par_comuna (IdRegion, Descripcion) values (33, 'Iquique')
insert into par_comuna (IdRegion, Descripcion) values (33, 'Alto Hospicio')
insert into par_comuna (IdRegion, Descripcion) values (33, 'Pozo Almonte')
insert into par_comuna (IdRegion, Descripcion) values (33, 'Camiña')
insert into par_comuna (IdRegion, Descripcion) values (33, 'Colchane')
insert into par_comuna (IdRegion, Descripcion) values (33, 'Huara')
insert into par_comuna (IdRegion, Descripcion) values (33, 'Pica')
insert into par_comuna (IdRegion, Descripcion) values (34, 'Antofagasta')
insert into par_comuna (IdRegion, Descripcion) values (34, 'Mejillones')
insert into par_comuna (IdRegion, Descripcion) values (34, 'Sierra Gorda')
insert into par_comuna (IdRegion, Descripcion) values (34, 'Taltal')
insert into par_comuna (IdRegion, Descripcion) values (34, 'Calama')
insert into par_comuna (IdRegion, Descripcion) values (34, 'Ollagüe')
insert into par_comuna (IdRegion, Descripcion) values (34, 'San Pedro de Atacama')
insert into par_comuna (IdRegion, Descripcion) values (34, 'Tocopilla')
insert into par_comuna (IdRegion, Descripcion) values (34, 'Maria Elena')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Copiapó')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Caldera')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Tierra Amarilla')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Chañaral')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Diego de Almagro')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Vallenar')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Alto del Carmen')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Freirina')
insert into par_comuna (IdRegion, Descripcion) values (35, 'Huasco')
insert into par_comuna (IdRegion, Descripcion) values (35, 'La Serena')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Coquimbo')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Andacollo')
insert into par_comuna (IdRegion, Descripcion) values (36, 'La Higuera')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Paiguano')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Vicuña')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Illapel')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Canela')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Los Vilos')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Salamanca')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Ovalle')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Combarbalá')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Monte Patria')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Punitaqui')
insert into par_comuna (IdRegion, Descripcion) values (36, 'Rio Hurtado')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Valparaíso')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Casablanca')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Concón')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Juan Fernández')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Puchuncaví')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Quintero')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Viña del Mar')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Isla de Pascua')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Los Andes')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Calle Larga')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Rinconada')
insert into par_comuna (IdRegion, Descripcion) values (37, 'San Esteban')
insert into par_comuna (IdRegion, Descripcion) values (37, 'La Ligua')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Cabildo')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Papudo')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Petorca')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Zapallar')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Quillota')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Calera')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Hijuelas')
insert into par_comuna (IdRegion, Descripcion) values (37, 'La Cruz')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Nogales')
insert into par_comuna (IdRegion, Descripcion) values (37, 'San Antonio')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Algarrobo')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Cartagena')
insert into par_comuna (IdRegion, Descripcion) values (37, 'El Quisco')
insert into par_comuna (IdRegion, Descripcion) values (37, 'El Tabo')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Santo Domingo')
insert into par_comuna (IdRegion, Descripcion) values (37, 'San Felipe')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Catemu')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Llaillay')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Panquehue')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Putaendo')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Santa María')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Limache')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Quilpué')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Villa Alemana')
insert into par_comuna (IdRegion, Descripcion) values (37, 'Olmué')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Rancagua')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Codegua')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Coinco')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Coltauco')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Doñihue')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Graneros')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Las Cabras')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Machalí')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Malloa')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Mostazal')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Olivar')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Peumo')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Pichidegua')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Quinta de Tilcoco')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Rengo')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Requínoa')
insert into par_comuna (IdRegion, Descripcion) values (38, 'San vicente')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Pichilemu')
insert into par_comuna (IdRegion, Descripcion) values (38, 'La Estrella')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Litueche')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Marchihue')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Navidad')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Paredones')
insert into par_comuna (IdRegion, Descripcion) values (38, 'San Fernando')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Chépica')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Chimbarongo')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Lolol')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Nancagua')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Palmilla')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Peralillo')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Placila')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Pumanque')
insert into par_comuna (IdRegion, Descripcion) values (38, 'Santa Cruz')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Talca')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Constitución')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Curepto')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Empedrado')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Maule')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Pelarco')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Pencahue')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Río Claro')
insert into par_comuna (IdRegion, Descripcion) values (39, 'San Clemente')
insert into par_comuna (IdRegion, Descripcion) values (39, 'San Rafael')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Cauquenes')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Chanco')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Pelluhue')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Curicó')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Hualañe')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Licantén')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Molina')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Rauco')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Romeral')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Sagrada Familia')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Teno')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Vichuquén')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Linares')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Colbún')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Longaví')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Parral')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Retiro')
insert into par_comuna (IdRegion, Descripcion) values (39, 'San Javier')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Villa Alegre')
insert into par_comuna (IdRegion, Descripcion) values (39, 'Yerbas Buenas')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Concepción')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Coronel')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Chiguayante')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Florida')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Hualqui')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Lota')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Penco')
insert into par_comuna (IdRegion, Descripcion) values (40, 'San Pedro de la Paz')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Santa Juana')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Talcahuano')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Tomé')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Hualpén')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Lebu')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Arauco')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Cañete')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Contulmo')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Curanilahue')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Los Alamos')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Tirúa')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Los Angeles')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Antuco')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Cabrero')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Laja')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Mulchén')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Nacimiento')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Negrete')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Quilaco')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Quilleco')
insert into par_comuna (IdRegion, Descripcion) values (40, 'San Rosendo')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Santa Bárbara')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Tucapel')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Yumbel')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Alto Biobío')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Chillán')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Bulnes')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Cobquecura')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Coelemu')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Coihueco')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Chillán Viejo')
insert into par_comuna (IdRegion, Descripcion) values (40, 'El Carmen')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Ninhue')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Ñiquén')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Pemuco')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Pinto')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Portezuelo')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Quillón')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Quirihue')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Ránquil')
insert into par_comuna (IdRegion, Descripcion) values (40, 'San Carlos')
insert into par_comuna (IdRegion, Descripcion) values (40, 'San Fabián')
insert into par_comuna (IdRegion, Descripcion) values (40, 'San Ignacio')
insert into par_comuna (IdRegion, Descripcion) values (40, 'San Nicolás')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Treguaco')
insert into par_comuna (IdRegion, Descripcion) values (40, 'Yungay')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Temuco')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Carahue')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Cunco')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Cucarrehue')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Freire')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Galvarino')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Gorbea')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Lautaro')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Loncoche')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Melipeuco')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Nueva Imperial')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Padre Las Casas')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Perquenco')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Pitrufquén')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Pucón')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Saavedra')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Teodoro Schmidt')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Toltén')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Vilcún')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Villarica')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Cholchol')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Angol')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Collipulli')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Curacautín')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Ercilla')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Lonquimay')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Los Sauces')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Lumaco')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Purén')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Renaico')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Traiquén')
insert into par_comuna (IdRegion, Descripcion) values (41, 'Victoria')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Valdivia')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Corral')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Lanco')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Los Lagos')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Máfil')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Mariquina')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Paillaco')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Panquipulli')
insert into par_comuna (IdRegion, Descripcion) values (42, 'La Unión')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Futrono')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Lago Ranco')
insert into par_comuna (IdRegion, Descripcion) values (42, 'Río Bueno')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Puerto Montt')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Calbuco')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Cochamó')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Fresia')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Frutillar')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Los Muermos')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Llanquihue')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Maullín')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Puerto Varas')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Castro')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Ancud')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Chonchi')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Curaco de Vélez')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Dalcahue')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Puqueldón')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Queilén')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Quellón')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Quemchi')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Quinchao')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Osorno')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Puerto Octay')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Purranque')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Puyehue')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Río Negro')
insert into par_comuna (IdRegion, Descripcion) values (43, 'San Juan de la Costa')
insert into par_comuna (IdRegion, Descripcion) values (43, 'San Palbo')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Chaitén')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Futaleufú')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Hualaihué')
insert into par_comuna (IdRegion, Descripcion) values (43, 'Palena')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Coihaique')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Lago Verde')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Aisén')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Cisnes')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Guaitecas')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Cochrane')
insert into par_comuna (IdRegion, Descripcion) values (44, 'O''higgins')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Tortel')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Rio Chico')
insert into par_comuna (IdRegion, Descripcion) values (44, 'Río Ibáñez')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Punta Arenas')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Laguna Blanca')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Río Verde')
insert into par_comuna (IdRegion, Descripcion) values (45, 'San Gregorio')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Cabo de Hornos (Ex-Navarino)')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Antártica')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Porvenir')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Primavera')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Timaukel')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Natales')
insert into par_comuna (IdRegion, Descripcion) values (45, 'Torres del Paine')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Santiago')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Cerrillos')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Cerro Navia')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Conchalí')
insert into par_comuna (IdRegion, Descripcion) values (46, 'El Bosque')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Estación Central')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Huechuraba')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Independencia')
insert into par_comuna (IdRegion, Descripcion) values (46, 'La Cisterna')
insert into par_comuna (IdRegion, Descripcion) values (46, 'La Florida')
insert into par_comuna (IdRegion, Descripcion) values (46, 'La Granja')
insert into par_comuna (IdRegion, Descripcion) values (46, 'La Pintana')
insert into par_comuna (IdRegion, Descripcion) values (46, 'La Reina')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Las Condes')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Lo Barnechea')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Lo Espejo')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Lo Prado')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Macul')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Maipú')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Ñuñoa')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Pedro Aguirre Cerda')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Peñalolén')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Providencia')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Pudahuel')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Quilicura')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Quinta Normal')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Recoleta')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Renca')
insert into par_comuna (IdRegion, Descripcion) values (46, 'San Joaquín')
insert into par_comuna (IdRegion, Descripcion) values (46, 'San Miguel')
insert into par_comuna (IdRegion, Descripcion) values (46, 'San Ramón')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Vitacura')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Puente Alto')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Pirque')
insert into par_comuna (IdRegion, Descripcion) values (46, 'San José de Maipú')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Colina')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Lampa')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Tíltil')
insert into par_comuna (IdRegion, Descripcion) values (46, 'San Bernardo')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Buin')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Calera de Tango')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Paine')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Melipilla')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Algué')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Curacaví')
insert into par_comuna (IdRegion, Descripcion) values (46, 'María Pinto')
insert into par_comuna (IdRegion, Descripcion) values (46, 'San Pedro')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Talagante')
insert into par_comuna (IdRegion, Descripcion) values (46, 'El Monte')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Isla de Maipo')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Padre Hurtado')
insert into par_comuna (IdRegion, Descripcion) values (46, 'Peñaflor')